version: '3.8'

services:
  web:
    image: odoo:latest
    container_name: odoo-web
    ports:
      - "8071:8069"
    volumes:
      - odoo_data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
    environment:
      - HOST=host.docker.internal  # Connect to local PostgreSQL
      - USER=odoo
      - PASSWORD=odoo
      - DATABASE=odoo

volumes:
  odoo_data:
